/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter_agent (void);
GtkWidget* create_modifier_agent (void);
GtkWidget* create_affichage_agent (void);
GtkWidget* create_liste_reservations_agent (void);
