/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouter_agent (void)
{
  GtkWidget *ajouter_agent;
  GtkWidget *fixed1;
  GtkWidget *id_entry;
  GtkWidget *nom_entry;
  GtkWidget *prenom_entry;
  GtkWidget *email_entry;
  GtkWidget *num_entry;
  GtkObject *spin_jour_adj;
  GtkWidget *spin_jour;
  GtkObject *spin_mois_adj;
  GtkWidget *spin_mois;
  GtkObject *spin_annee_adj;
  GtkWidget *spin_annee;
  GtkWidget *homme_radio;
  GSList *homme_radio_group = NULL;
  GtkWidget *femme_radio;
  GtkWidget *num_ajout_agent;
  GtkWidget *region_ajout_agent;
  GtkWidget *prenom_ajout_agent;
  GtkWidget *nom_ajout_agent;
  GtkWidget *id_ajout_agent;
  GtkWidget *date_ajout_agent;
  GtkWidget *sexe_ajout_agent;
  GtkWidget *email_ajout_agent;
  GtkWidget *services_ajout_agent;
  GtkWidget *recharge;
  GtkWidget *lavage;
  GtkWidget *assistance;
  GtkWidget *gonflage;
  GtkWidget *annuler_btn_agent;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11;
  GtkWidget *ajouter_btn_agent;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label10;
  GtkWidget *msg;
  GtkWidget *retour_ajout_agent;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label12;
  GtkWidget *acceuil_ajout_agent;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label13;
  GtkWidget *combobox_region;

  ajouter_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_agent), _("Ajouter agent"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouter_agent), fixed1);

  id_entry = gtk_entry_new ();
  gtk_widget_show (id_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), id_entry, 288, 120);
  gtk_widget_set_size_request (id_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_entry), 8226);

  nom_entry = gtk_entry_new ();
  gtk_widget_show (nom_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), nom_entry, 288, 168);
  gtk_widget_set_size_request (nom_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_entry), 8226);

  prenom_entry = gtk_entry_new ();
  gtk_widget_show (prenom_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), prenom_entry, 288, 216);
  gtk_widget_set_size_request (prenom_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_entry), 8226);

  email_entry = gtk_entry_new ();
  gtk_widget_show (email_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), email_entry, 296, 464);
  gtk_widget_set_size_request (email_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (email_entry), 8226);

  num_entry = gtk_entry_new ();
  gtk_widget_show (num_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), num_entry, 296, 512);
  gtk_widget_set_size_request (num_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (num_entry), 8226);

  spin_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spin_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spin_jour_adj), 1, 0);
  gtk_widget_show (spin_jour);
  gtk_fixed_put (GTK_FIXED (fixed1), spin_jour, 288, 280);
  gtk_widget_set_size_request (spin_jour, 60, 27);

  spin_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spin_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spin_mois_adj), 1, 0);
  gtk_widget_show (spin_mois);
  gtk_fixed_put (GTK_FIXED (fixed1), spin_mois, 368, 280);
  gtk_widget_set_size_request (spin_mois, 64, 27);

  spin_annee_adj = gtk_adjustment_new (1, 1990, 2002, 1, 10, 10);
  spin_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spin_annee_adj), 1, 0);
  gtk_widget_show (spin_annee);
  gtk_fixed_put (GTK_FIXED (fixed1), spin_annee, 448, 280);
  gtk_widget_set_size_request (spin_annee, 96, 27);

  homme_radio = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (homme_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), homme_radio, 288, 352);
  gtk_widget_set_size_request (homme_radio, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (homme_radio), homme_radio_group);
  homme_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (homme_radio));

  femme_radio = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (femme_radio);
  gtk_fixed_put (GTK_FIXED (fixed1), femme_radio, 416, 352);
  gtk_widget_set_size_request (femme_radio, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femme_radio), homme_radio_group);
  homme_radio_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femme_radio));

  num_ajout_agent = gtk_label_new (_("T\303\251l\303\251phone:"));
  gtk_widget_show (num_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), num_ajout_agent, 136, 512);
  gtk_widget_set_size_request (num_ajout_agent, 129, 25);

  region_ajout_agent = gtk_label_new (_("R\303\251gion:"));
  gtk_widget_show (region_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), region_ajout_agent, 136, 408);
  gtk_widget_set_size_request (region_ajout_agent, 121, 25);

  prenom_ajout_agent = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (prenom_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), prenom_ajout_agent, 112, 216);
  gtk_widget_set_size_request (prenom_ajout_agent, 137, 25);

  nom_ajout_agent = gtk_label_new (_("Nom:"));
  gtk_widget_show (nom_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), nom_ajout_agent, 112, 168);
  gtk_widget_set_size_request (nom_ajout_agent, 137, 25);

  id_ajout_agent = gtk_label_new (_("ID:"));
  gtk_widget_show (id_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), id_ajout_agent, 120, 120);
  gtk_widget_set_size_request (id_ajout_agent, 129, 25);

  date_ajout_agent = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (date_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), date_ajout_agent, 96, 280);
  gtk_widget_set_size_request (date_ajout_agent, 161, 33);

  sexe_ajout_agent = gtk_label_new (_("Sexe:"));
  gtk_widget_show (sexe_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), sexe_ajout_agent, 136, 352);
  gtk_widget_set_size_request (sexe_ajout_agent, 105, 25);

  email_ajout_agent = gtk_label_new (_("Email:"));
  gtk_widget_show (email_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), email_ajout_agent, 144, 464);
  gtk_widget_set_size_request (email_ajout_agent, 113, 25);

  services_ajout_agent = gtk_label_new (_("Services:"));
  gtk_widget_show (services_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), services_ajout_agent, 136, 560);
  gtk_widget_set_size_request (services_ajout_agent, 129, 33);

  recharge = gtk_check_button_new_with_mnemonic (_("Recharge \303\251lectronique"));
  gtk_widget_show (recharge);
  gtk_fixed_put (GTK_FIXED (fixed1), recharge, 288, 616);
  gtk_widget_set_size_request (recharge, 192, 32);

  lavage = gtk_check_button_new_with_mnemonic (_("Lavage"));
  gtk_widget_show (lavage);
  gtk_fixed_put (GTK_FIXED (fixed1), lavage, 296, 576);
  gtk_widget_set_size_request (lavage, 118, 24);

  assistance = gtk_check_button_new_with_mnemonic (_("Assistance d\303\251pannage"));
  gtk_widget_show (assistance);
  gtk_fixed_put (GTK_FIXED (fixed1), assistance, 488, 616);
  gtk_widget_set_size_request (assistance, 184, 24);

  gonflage = gtk_check_button_new_with_mnemonic (_("Gonflage des pneus"));
  gtk_widget_show (gonflage);
  gtk_fixed_put (GTK_FIXED (fixed1), gonflage, 488, 576);
  gtk_widget_set_size_request (gonflage, 176, 24);

  annuler_btn_agent = gtk_button_new ();
  gtk_widget_show (annuler_btn_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), annuler_btn_agent, 592, 672);
  gtk_widget_set_size_request (annuler_btn_agent, 112, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (annuler_btn_agent), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);

  ajouter_btn_agent = gtk_button_new ();
  gtk_widget_show (ajouter_btn_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_btn_agent, 96, 672);
  gtk_widget_set_size_request (ajouter_btn_agent, 112, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter_btn_agent), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox1), label10, FALSE, FALSE, 0);

  msg = gtk_label_new ("");
  gtk_widget_show (msg);
  gtk_fixed_put (GTK_FIXED (fixed1), msg, 240, 672);
  gtk_widget_set_size_request (msg, 312, 57);

  retour_ajout_agent = gtk_button_new ();
  gtk_widget_show (retour_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), retour_ajout_agent, 40, 24);
  gtk_widget_set_size_request (retour_ajout_agent, 104, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retour_ajout_agent), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  acceuil_ajout_agent = gtk_button_new ();
  gtk_widget_show (acceuil_ajout_agent);
  gtk_fixed_put (GTK_FIXED (fixed1), acceuil_ajout_agent, 584, 32);
  gtk_widget_set_size_request (acceuil_ajout_agent, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (acceuil_ajout_agent), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox4), label13, FALSE, FALSE, 0);

  combobox_region = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_region);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox_region, 296, 408);
  gtk_widget_set_size_request (combobox_region, 152, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Centre_Ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Zone_Indus_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Azur_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Tunis_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region), _("Tunisia_Mall"));

  g_signal_connect ((gpointer) homme_radio, "toggled",
                    G_CALLBACK (on_homme_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) femme_radio, "toggled",
                    G_CALLBACK (on_femme_radio_toggled),
                    NULL);
  g_signal_connect ((gpointer) recharge, "toggled",
                    G_CALLBACK (on_recharge_toggled),
                    NULL);
  g_signal_connect ((gpointer) lavage, "toggled",
                    G_CALLBACK (on_lavage_toggled),
                    NULL);
  g_signal_connect ((gpointer) assistance, "toggled",
                    G_CALLBACK (on_assistance_toggled),
                    NULL);
  g_signal_connect ((gpointer) gonflage, "toggled",
                    G_CALLBACK (on_gonflage_toggled),
                    NULL);
  g_signal_connect ((gpointer) annuler_btn_agent, "clicked",
                    G_CALLBACK (on_annuler_btn_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_btn_agent, "clicked",
                    G_CALLBACK (on_ajouter_btn_agent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_agent, ajouter_agent, "ajouter_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouter_agent, id_entry, "id_entry");
  GLADE_HOOKUP_OBJECT (ajouter_agent, nom_entry, "nom_entry");
  GLADE_HOOKUP_OBJECT (ajouter_agent, prenom_entry, "prenom_entry");
  GLADE_HOOKUP_OBJECT (ajouter_agent, email_entry, "email_entry");
  GLADE_HOOKUP_OBJECT (ajouter_agent, num_entry, "num_entry");
  GLADE_HOOKUP_OBJECT (ajouter_agent, spin_jour, "spin_jour");
  GLADE_HOOKUP_OBJECT (ajouter_agent, spin_mois, "spin_mois");
  GLADE_HOOKUP_OBJECT (ajouter_agent, spin_annee, "spin_annee");
  GLADE_HOOKUP_OBJECT (ajouter_agent, homme_radio, "homme_radio");
  GLADE_HOOKUP_OBJECT (ajouter_agent, femme_radio, "femme_radio");
  GLADE_HOOKUP_OBJECT (ajouter_agent, num_ajout_agent, "num_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, region_ajout_agent, "region_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, prenom_ajout_agent, "prenom_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, nom_ajout_agent, "nom_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, id_ajout_agent, "id_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, date_ajout_agent, "date_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, sexe_ajout_agent, "sexe_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, email_ajout_agent, "email_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, services_ajout_agent, "services_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, recharge, "recharge");
  GLADE_HOOKUP_OBJECT (ajouter_agent, lavage, "lavage");
  GLADE_HOOKUP_OBJECT (ajouter_agent, assistance, "assistance");
  GLADE_HOOKUP_OBJECT (ajouter_agent, gonflage, "gonflage");
  GLADE_HOOKUP_OBJECT (ajouter_agent, annuler_btn_agent, "annuler_btn_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajouter_agent, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajouter_agent, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajouter_agent, label11, "label11");
  GLADE_HOOKUP_OBJECT (ajouter_agent, ajouter_btn_agent, "ajouter_btn_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajouter_agent, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajouter_agent, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajouter_agent, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajouter_agent, msg, "msg");
  GLADE_HOOKUP_OBJECT (ajouter_agent, retour_ajout_agent, "retour_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ajouter_agent, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ajouter_agent, image3, "image3");
  GLADE_HOOKUP_OBJECT (ajouter_agent, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajouter_agent, acceuil_ajout_agent, "acceuil_ajout_agent");
  GLADE_HOOKUP_OBJECT (ajouter_agent, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ajouter_agent, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajouter_agent, image4, "image4");
  GLADE_HOOKUP_OBJECT (ajouter_agent, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajouter_agent, combobox_region, "combobox_region");

  return ajouter_agent;
}

GtkWidget*
create_modifier_agent (void)
{
  GtkWidget *modifier_agent;
  GtkWidget *fixed2;
  GtkWidget *num_entry_modif;
  GtkWidget *email_entry_modif;
  GtkObject *spin_jour_modif_adj;
  GtkWidget *spin_jour_modif;
  GtkObject *spin_mois_modif_adj;
  GtkWidget *spin_mois_modif;
  GtkObject *spin_annee_modif_adj;
  GtkWidget *spin_annee_modif;
  GtkWidget *nom_entry_modif;
  GtkWidget *prenom_entry_modif;
  GtkWidget *acceuil_modif_agent;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *retour_modif_agent;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label16;
  GtkWidget *sexe_agent_modif;
  GtkWidget *region_ajout_moodif;
  GtkWidget *services_agent_modif;
  GtkWidget *bouton_modifier_agent;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label14;
  GtkWidget *radio_homme_modif;
  GSList *radio_homme_modif_group = NULL;
  GtkWidget *radio_femme_modif;
  GtkWidget *lavage_modif;
  GtkWidget *recharge_modif;
  GtkWidget *gonflage_modif;
  GtkWidget *assistance_modif;
  GtkWidget *bouton_annuler_modif;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label15;
  GtkWidget *tel_agent_modif;
  GtkWidget *email_agent_modif;
  GtkWidget *msg_modif;
  GtkWidget *nom_agent_modif;
  GtkWidget *prenom_agent_modif;
  GtkWidget *date_agent_modif;
  GtkWidget *combobox_region_modif;

  modifier_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_agent), _("Modifier un agent"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modifier_agent), fixed2);

  num_entry_modif = gtk_entry_new ();
  gtk_widget_show (num_entry_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), num_entry_modif, 256, 464);
  gtk_widget_set_size_request (num_entry_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (num_entry_modif), 8226);

  email_entry_modif = gtk_entry_new ();
  gtk_widget_show (email_entry_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), email_entry_modif, 256, 528);
  gtk_widget_set_size_request (email_entry_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (email_entry_modif), 8226);

  spin_jour_modif_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spin_jour_modif = gtk_spin_button_new (GTK_ADJUSTMENT (spin_jour_modif_adj), 1, 0);
  gtk_widget_show (spin_jour_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), spin_jour_modif, 256, 256);
  gtk_widget_set_size_request (spin_jour_modif, 64, 24);

  spin_mois_modif_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spin_mois_modif = gtk_spin_button_new (GTK_ADJUSTMENT (spin_mois_modif_adj), 1, 0);
  gtk_widget_show (spin_mois_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), spin_mois_modif, 336, 256);
  gtk_widget_set_size_request (spin_mois_modif, 72, 24);

  spin_annee_modif_adj = gtk_adjustment_new (1, 1990, 2002, 1, 10, 10);
  spin_annee_modif = gtk_spin_button_new (GTK_ADJUSTMENT (spin_annee_modif_adj), 1, 0);
  gtk_widget_show (spin_annee_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), spin_annee_modif, 424, 256);
  gtk_widget_set_size_request (spin_annee_modif, 80, 24);

  nom_entry_modif = gtk_entry_new ();
  gtk_widget_show (nom_entry_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), nom_entry_modif, 256, 104);
  gtk_widget_set_size_request (nom_entry_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_entry_modif), 8226);

  prenom_entry_modif = gtk_entry_new ();
  gtk_widget_show (prenom_entry_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom_entry_modif, 256, 176);
  gtk_widget_set_size_request (prenom_entry_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom_entry_modif), 8226);

  acceuil_modif_agent = gtk_button_new ();
  gtk_widget_show (acceuil_modif_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), acceuil_modif_agent, 576, 24);
  gtk_widget_set_size_request (acceuil_modif_agent, 104, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (acceuil_modif_agent), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  retour_modif_agent = gtk_button_new ();
  gtk_widget_show (retour_modif_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), retour_modif_agent, 48, 24);
  gtk_widget_set_size_request (retour_modif_agent, 104, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (retour_modif_agent), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox7), label16, FALSE, FALSE, 0);

  sexe_agent_modif = gtk_label_new (_("Sexe:"));
  gtk_widget_show (sexe_agent_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), sexe_agent_modif, 112, 320);
  gtk_widget_set_size_request (sexe_agent_modif, 97, 25);

  region_ajout_moodif = gtk_label_new (_("R\303\251gion:"));
  gtk_widget_show (region_ajout_moodif);
  gtk_fixed_put (GTK_FIXED (fixed2), region_ajout_moodif, 96, 384);
  gtk_widget_set_size_request (region_ajout_moodif, 129, 25);

  services_agent_modif = gtk_label_new (_("Services:"));
  gtk_widget_show (services_agent_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), services_agent_modif, 112, 600);
  gtk_widget_set_size_request (services_agent_modif, 121, 25);

  bouton_modifier_agent = gtk_button_new ();
  gtk_widget_show (bouton_modifier_agent);
  gtk_fixed_put (GTK_FIXED (fixed2), bouton_modifier_agent, 80, 696);
  gtk_widget_set_size_request (bouton_modifier_agent, 112, 37);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (bouton_modifier_agent), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox5), label14, FALSE, FALSE, 0);

  radio_homme_modif = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radio_homme_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), radio_homme_modif, 256, 328);
  gtk_widget_set_size_request (radio_homme_modif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_homme_modif), radio_homme_modif_group);
  radio_homme_modif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_homme_modif));

  radio_femme_modif = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radio_femme_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), radio_femme_modif, 384, 328);
  gtk_widget_set_size_request (radio_femme_modif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_femme_modif), radio_homme_modif_group);
  radio_homme_modif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_femme_modif));

  lavage_modif = gtk_check_button_new_with_mnemonic (_("Lavage"));
  gtk_widget_show (lavage_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), lavage_modif, 256, 600);
  gtk_widget_set_size_request (lavage_modif, 118, 24);

  recharge_modif = gtk_check_button_new_with_mnemonic (_("Recharge \303\251lectronique"));
  gtk_widget_show (recharge_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), recharge_modif, 440, 600);
  gtk_widget_set_size_request (recharge_modif, 192, 24);

  gonflage_modif = gtk_check_button_new_with_mnemonic (_("Gonflage des pneus"));
  gtk_widget_show (gonflage_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), gonflage_modif, 256, 648);
  gtk_widget_set_size_request (gonflage_modif, 168, 24);

  assistance_modif = gtk_check_button_new_with_mnemonic (_("Assistance d\303\251pannage"));
  gtk_widget_show (assistance_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), assistance_modif, 440, 648);
  gtk_widget_set_size_request (assistance_modif, 184, 24);

  bouton_annuler_modif = gtk_button_new ();
  gtk_widget_show (bouton_annuler_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), bouton_annuler_modif, 576, 696);
  gtk_widget_set_size_request (bouton_annuler_modif, 112, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (bouton_annuler_modif), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox6), label15, FALSE, FALSE, 0);

  tel_agent_modif = gtk_label_new (_("T\303\251l\303\251phone:"));
  gtk_widget_show (tel_agent_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), tel_agent_modif, 104, 464);
  gtk_widget_set_size_request (tel_agent_modif, 137, 25);

  email_agent_modif = gtk_label_new (_("Email:"));
  gtk_widget_show (email_agent_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), email_agent_modif, 120, 528);
  gtk_widget_set_size_request (email_agent_modif, 113, 25);

  msg_modif = gtk_label_new ("");
  gtk_widget_show (msg_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), msg_modif, 224, 688);
  gtk_widget_set_size_request (msg_modif, 336, 64);

  nom_agent_modif = gtk_label_new (_("Nom:"));
  gtk_widget_show (nom_agent_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), nom_agent_modif, 96, 104);
  gtk_widget_set_size_request (nom_agent_modif, 113, 25);

  prenom_agent_modif = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (prenom_agent_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom_agent_modif, 88, 176);
  gtk_widget_set_size_request (prenom_agent_modif, 129, 25);

  date_agent_modif = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (date_agent_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), date_agent_modif, 64, 256);
  gtk_widget_set_size_request (date_agent_modif, 161, 25);

  combobox_region_modif = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_region_modif);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_region_modif, 256, 384);
  gtk_widget_set_size_request (combobox_region_modif, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Centre_Ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Zone_Indus_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Azur_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Tunis_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_region_modif), _("Tunisia_Mall"));

  g_signal_connect ((gpointer) bouton_modifier_agent, "clicked",
                    G_CALLBACK (on_bouton_modifier_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) radio_homme_modif, "toggled",
                    G_CALLBACK (on_radio_homme_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_femme_modif, "toggled",
                    G_CALLBACK (on_radio_femme_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) lavage_modif, "toggled",
                    G_CALLBACK (on_lavage_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) recharge_modif, "toggled",
                    G_CALLBACK (on_recharge_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) gonflage_modif, "toggled",
                    G_CALLBACK (on_gonflage_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) assistance_modif, "toggled",
                    G_CALLBACK (on_assistance_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) bouton_annuler_modif, "clicked",
                    G_CALLBACK (on_bouton_annuler_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_agent, modifier_agent, "modifier_agent");
  GLADE_HOOKUP_OBJECT (modifier_agent, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modifier_agent, num_entry_modif, "num_entry_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, email_entry_modif, "email_entry_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, spin_jour_modif, "spin_jour_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, spin_mois_modif, "spin_mois_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, spin_annee_modif, "spin_annee_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, nom_entry_modif, "nom_entry_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, prenom_entry_modif, "prenom_entry_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, acceuil_modif_agent, "acceuil_modif_agent");
  GLADE_HOOKUP_OBJECT (modifier_agent, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modifier_agent, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modifier_agent, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifier_agent, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier_agent, retour_modif_agent, "retour_modif_agent");
  GLADE_HOOKUP_OBJECT (modifier_agent, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier_agent, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier_agent, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifier_agent, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier_agent, sexe_agent_modif, "sexe_agent_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, region_ajout_moodif, "region_ajout_moodif");
  GLADE_HOOKUP_OBJECT (modifier_agent, services_agent_modif, "services_agent_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, bouton_modifier_agent, "bouton_modifier_agent");
  GLADE_HOOKUP_OBJECT (modifier_agent, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modifier_agent, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modifier_agent, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifier_agent, label14, "label14");
  GLADE_HOOKUP_OBJECT (modifier_agent, radio_homme_modif, "radio_homme_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, radio_femme_modif, "radio_femme_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, lavage_modif, "lavage_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, recharge_modif, "recharge_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, gonflage_modif, "gonflage_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, assistance_modif, "assistance_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, bouton_annuler_modif, "bouton_annuler_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifier_agent, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifier_agent, image6, "image6");
  GLADE_HOOKUP_OBJECT (modifier_agent, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier_agent, tel_agent_modif, "tel_agent_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, email_agent_modif, "email_agent_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, msg_modif, "msg_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, nom_agent_modif, "nom_agent_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, prenom_agent_modif, "prenom_agent_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, date_agent_modif, "date_agent_modif");
  GLADE_HOOKUP_OBJECT (modifier_agent, combobox_region_modif, "combobox_region_modif");

  return modifier_agent;
}

GtkWidget*
create_affichage_agent (void)
{
  GtkWidget *affichage_agent;
  GtkWidget *fixed3;
  GtkWidget *recherche_id_entry;
  GtkWidget *recherche_agent;
  GtkWidget *filtrer_texte;
  GtkWidget *treeview_affichage;
  GtkWidget *retour_affichage_agent;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label22;
  GtkWidget *acceuil_affichage_agent;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label23;
  GtkWidget *combobox_filtre;
  GtkWidget *afficher_agents;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label21;
  GtkWidget *bouton_rechercher_agent;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label19;
  GtkWidget *bouton_filtrer_agent;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label27;
  GtkWidget *Ajouter_agent_affichage;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label24;
  GtkWidget *modifier_agent_affichage;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label25;
  GtkWidget *supprimer;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label26;

  affichage_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage_agent), _("Liste des agents"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (affichage_agent), fixed3);

  recherche_id_entry = gtk_entry_new ();
  gtk_widget_show (recherche_id_entry);
  gtk_fixed_put (GTK_FIXED (fixed3), recherche_id_entry, 248, 112);
  gtk_widget_set_size_request (recherche_id_entry, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (recherche_id_entry), 8226);

  recherche_agent = gtk_label_new (_("Selectionner un agent"));
  gtk_widget_show (recherche_agent);
  gtk_fixed_put (GTK_FIXED (fixed3), recherche_agent, 0, 112);
  gtk_widget_set_size_request (recherche_agent, 264, 33);

  filtrer_texte = gtk_label_new (_("Filtrer par r\303\251gion"));
  gtk_widget_show (filtrer_texte);
  gtk_fixed_put (GTK_FIXED (fixed3), filtrer_texte, 24, 208);
  gtk_widget_set_size_request (filtrer_texte, 224, 33);

  treeview_affichage = gtk_tree_view_new ();
  gtk_widget_show (treeview_affichage);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview_affichage, 64, 392);
  gtk_widget_set_size_request (treeview_affichage, 688, 248);

  retour_affichage_agent = gtk_button_new ();
  gtk_widget_show (retour_affichage_agent);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_affichage_agent, 24, 24);
  gtk_widget_set_size_request (retour_affichage_agent, 96, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (retour_affichage_agent), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox11), label22, FALSE, FALSE, 0);

  acceuil_affichage_agent = gtk_button_new ();
  gtk_widget_show (acceuil_affichage_agent);
  gtk_fixed_put (GTK_FIXED (fixed3), acceuil_affichage_agent, 680, 24);
  gtk_widget_set_size_request (acceuil_affichage_agent, 96, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (acceuil_affichage_agent), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox12), label23, FALSE, FALSE, 0);

  combobox_filtre = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_filtre);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_filtre, 248, 200);
  gtk_widget_set_size_request (combobox_filtre, 232, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Centre_Ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Zone_Indus_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Azur_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Tunis_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_filtre), _("Tunisia_Mall"));

  afficher_agents = gtk_button_new ();
  gtk_widget_show (afficher_agents);
  gtk_fixed_put (GTK_FIXED (fixed3), afficher_agents, 344, 320);
  gtk_widget_set_size_request (afficher_agents, 120, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (afficher_agents), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Afficher "));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox10), label21, FALSE, FALSE, 0);

  bouton_rechercher_agent = gtk_button_new ();
  gtk_widget_show (bouton_rechercher_agent);
  gtk_fixed_put (GTK_FIXED (fixed3), bouton_rechercher_agent, 512, 112);
  gtk_widget_set_size_request (bouton_rechercher_agent, 104, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (bouton_rechercher_agent), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  bouton_filtrer_agent = gtk_button_new ();
  gtk_widget_show (bouton_filtrer_agent);
  gtk_fixed_put (GTK_FIXED (fixed3), bouton_filtrer_agent, 512, 200);
  gtk_widget_set_size_request (bouton_filtrer_agent, 112, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (bouton_filtrer_agent), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Filtrer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox16), label27, FALSE, FALSE, 0);

  Ajouter_agent_affichage = gtk_button_new ();
  gtk_widget_show (Ajouter_agent_affichage);
  gtk_fixed_put (GTK_FIXED (fixed3), Ajouter_agent_affichage, 168, 696);
  gtk_widget_set_size_request (Ajouter_agent_affichage, 112, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (Ajouter_agent_affichage), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox13), label24, FALSE, FALSE, 0);

  modifier_agent_affichage = gtk_button_new ();
  gtk_widget_show (modifier_agent_affichage);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier_agent_affichage, 352, 696);
  gtk_widget_set_size_request (modifier_agent_affichage, 112, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (modifier_agent_affichage), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox14), label25, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimer, 536, 696);
  gtk_widget_set_size_request (supprimer, 112, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox15), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_affichage, "row_activated",
                    G_CALLBACK (on_treeview_affichage_row_activated),
                    NULL);
  g_signal_connect ((gpointer) afficher_agents, "clicked",
                    G_CALLBACK (on_afficher_agents_clicked),
                    NULL);
  g_signal_connect ((gpointer) bouton_rechercher_agent, "clicked",
                    G_CALLBACK (on_bouton_rechercher_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) bouton_filtrer_agent, "clicked",
                    G_CALLBACK (on_bouton_filtrer_agent_clicked),
                    NULL);
  g_signal_connect ((gpointer) Ajouter_agent_affichage, "clicked",
                    G_CALLBACK (on_Ajouter_agent_affichage_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_agent_affichage, "clicked",
                    G_CALLBACK (on_modifier_agent_affichage_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage_agent, affichage_agent, "affichage_agent");
  GLADE_HOOKUP_OBJECT (affichage_agent, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (affichage_agent, recherche_id_entry, "recherche_id_entry");
  GLADE_HOOKUP_OBJECT (affichage_agent, recherche_agent, "recherche_agent");
  GLADE_HOOKUP_OBJECT (affichage_agent, filtrer_texte, "filtrer_texte");
  GLADE_HOOKUP_OBJECT (affichage_agent, treeview_affichage, "treeview_affichage");
  GLADE_HOOKUP_OBJECT (affichage_agent, retour_affichage_agent, "retour_affichage_agent");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (affichage_agent, image11, "image11");
  GLADE_HOOKUP_OBJECT (affichage_agent, label22, "label22");
  GLADE_HOOKUP_OBJECT (affichage_agent, acceuil_affichage_agent, "acceuil_affichage_agent");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (affichage_agent, image12, "image12");
  GLADE_HOOKUP_OBJECT (affichage_agent, label23, "label23");
  GLADE_HOOKUP_OBJECT (affichage_agent, combobox_filtre, "combobox_filtre");
  GLADE_HOOKUP_OBJECT (affichage_agent, afficher_agents, "afficher_agents");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (affichage_agent, image10, "image10");
  GLADE_HOOKUP_OBJECT (affichage_agent, label21, "label21");
  GLADE_HOOKUP_OBJECT (affichage_agent, bouton_rechercher_agent, "bouton_rechercher_agent");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (affichage_agent, image9, "image9");
  GLADE_HOOKUP_OBJECT (affichage_agent, label19, "label19");
  GLADE_HOOKUP_OBJECT (affichage_agent, bouton_filtrer_agent, "bouton_filtrer_agent");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (affichage_agent, image16, "image16");
  GLADE_HOOKUP_OBJECT (affichage_agent, label27, "label27");
  GLADE_HOOKUP_OBJECT (affichage_agent, Ajouter_agent_affichage, "Ajouter_agent_affichage");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (affichage_agent, image13, "image13");
  GLADE_HOOKUP_OBJECT (affichage_agent, label24, "label24");
  GLADE_HOOKUP_OBJECT (affichage_agent, modifier_agent_affichage, "modifier_agent_affichage");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (affichage_agent, image14, "image14");
  GLADE_HOOKUP_OBJECT (affichage_agent, label25, "label25");
  GLADE_HOOKUP_OBJECT (affichage_agent, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (affichage_agent, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (affichage_agent, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (affichage_agent, image15, "image15");
  GLADE_HOOKUP_OBJECT (affichage_agent, label26, "label26");

  return affichage_agent;
}

GtkWidget*
create_liste_reservations_agent (void)
{
  GtkWidget *liste_reservations_agent;
  GtkWidget *fixed4;
  GtkObject *spin_jour_R_adj;
  GtkWidget *spin_jour_R;
  GtkObject *spin_mois_R_adj;
  GtkWidget *spin_mois_R;
  GtkObject *spin_annee_R_adj;
  GtkWidget *spin_annee_R;
  GtkWidget *treeview_R;
  GtkWidget *rechercher_date;
  GtkWidget *bouton_recherche_date;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label29;
  GtkWidget *bouton_retour_R;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label30;
  GtkWidget *bouton_acceuil_R;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label31;

  liste_reservations_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (liste_reservations_agent), _("R\303\251servations"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (liste_reservations_agent), fixed4);

  spin_jour_R_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spin_jour_R = gtk_spin_button_new (GTK_ADJUSTMENT (spin_jour_R_adj), 1, 0);
  gtk_widget_show (spin_jour_R);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_jour_R, 232, 104);
  gtk_widget_set_size_request (spin_jour_R, 64, 24);

  spin_mois_R_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spin_mois_R = gtk_spin_button_new (GTK_ADJUSTMENT (spin_mois_R_adj), 1, 0);
  gtk_widget_show (spin_mois_R);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_mois_R, 328, 104);
  gtk_widget_set_size_request (spin_mois_R, 72, 24);

  spin_annee_R_adj = gtk_adjustment_new (2024, 2024, 2090, 1, 10, 10);
  spin_annee_R = gtk_spin_button_new (GTK_ADJUSTMENT (spin_annee_R_adj), 1, 0);
  gtk_widget_show (spin_annee_R);
  gtk_fixed_put (GTK_FIXED (fixed4), spin_annee_R, 432, 104);
  gtk_widget_set_size_request (spin_annee_R, 88, 24);

  treeview_R = gtk_tree_view_new ();
  gtk_widget_show (treeview_R);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview_R, 136, 192);
  gtk_widget_set_size_request (treeview_R, 496, 312);

  rechercher_date = gtk_label_new (_("Selectionnez une date"));
  gtk_widget_show (rechercher_date);
  gtk_fixed_put (GTK_FIXED (fixed4), rechercher_date, 0, 96);
  gtk_widget_set_size_request (rechercher_date, 224, 33);

  bouton_recherche_date = gtk_button_new ();
  gtk_widget_show (bouton_recherche_date);
  gtk_fixed_put (GTK_FIXED (fixed4), bouton_recherche_date, 552, 96);
  gtk_widget_set_size_request (bouton_recherche_date, 104, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (bouton_recherche_date), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox17), label29, FALSE, FALSE, 0);

  bouton_retour_R = gtk_button_new ();
  gtk_widget_show (bouton_retour_R);
  gtk_fixed_put (GTK_FIXED (fixed4), bouton_retour_R, 32, 32);
  gtk_widget_set_size_request (bouton_retour_R, 90, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (bouton_retour_R), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox18), label30, FALSE, FALSE, 0);

  bouton_acceuil_R = gtk_button_new ();
  gtk_widget_show (bouton_acceuil_R);
  gtk_fixed_put (GTK_FIXED (fixed4), bouton_acceuil_R, 616, 32);
  gtk_widget_set_size_request (bouton_acceuil_R, 88, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (bouton_acceuil_R), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox19), label31, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_R, "row_activated",
                    G_CALLBACK (on_treeview_R_row_activated),
                    NULL);
  g_signal_connect ((gpointer) bouton_recherche_date, "clicked",
                    G_CALLBACK (on_bouton_recherche_date_clicked),
                    NULL);
  g_signal_connect ((gpointer) bouton_retour_R, "clicked",
                    G_CALLBACK (on_bouton_retour_R_clicked),
                    NULL);
  g_signal_connect ((gpointer) bouton_acceuil_R, "clicked",
                    G_CALLBACK (on_bouton_acceuil_R_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_reservations_agent, liste_reservations_agent, "liste_reservations_agent");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, spin_jour_R, "spin_jour_R");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, spin_mois_R, "spin_mois_R");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, spin_annee_R, "spin_annee_R");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, treeview_R, "treeview_R");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, rechercher_date, "rechercher_date");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, bouton_recherche_date, "bouton_recherche_date");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, image17, "image17");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, label29, "label29");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, bouton_retour_R, "bouton_retour_R");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, image18, "image18");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, label30, "label30");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, bouton_acceuil_R, "bouton_acceuil_R");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, image19, "image19");
  GLADE_HOOKUP_OBJECT (liste_reservations_agent, label31, "label31");

  return liste_reservations_agent;
}

